#!/bin/bash

if amixer get Master | grep -q off; then
	echo " "
	echo " "
	exit 0
fi

#vol=$(amixer sget $BLOCK_INSTANCE | grep "Left" | grep -o "[0-9]*[0-9]%" | grep -o "[0-9]*[0-9]")
vol=$(pactl list sinks | grep "Volume: front-left" | grep -o "[0-9]*%" | head -n1)

if [ ${vol:0:2} -ge 66 ]; then
	label=""
elif [ ${vol:0:2} -ge 33 ]; then
	label=""
else
	label=""
fi

echo $label $vol
echo $label $vol

