#!/bin/sh

ln -sv ./bash_aliases $HOME/.bash_aliases
ln -sv ./bash_logout $HOME/.bash_logout
ln -sv ./bash_profile $HOME/.bash_profile
ln -sv ./bash_env $HOME/.bash_env
ln -sv ./bashrc $HOME/.bashrc
ln -sv ./bin $HOME/.local/bin
ln -sv ./config $HOME/.config
