#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="$1"
warn=75
crit=90
used_perc=$(df -h -P -l "$DIR" | awk '/\/.*/ {print$5}')
used_perc="$(echo $used_perc | grep -o "[0-9]*")"

if [ "$used_perc" -ge "$crit" ]; then
	echo 3
elif [ "$used_perc" -ge "$warn" ]; then
	echo 2
else
	echo 1
fi
