#!/bin/bash

alias po="sudo poweroff"
alias rb="sudo reboot"

alias ls="ls --color=auto"
alias la="ls -a"
alias lal="ls -alh"
alias ll="ls -lh"
alias rm="rm -I"
alias rr="rm -Ir"
alias mv="mv -v"
alias rmdir="rmdir -v"
alias mkdir="mkdir -pv"
alias df="df -h"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias \:q="exit"
alias ZZ="exit"

function cd () {
    builtin cd "$@" && ls
}

function cu() {
    i=0
    [ -z $1 ] && cd ../

    if [ ! -z $1 ]; then
        while [ $i -lt $1 ]
        do
            cd ../
            i=$(($i+1))
        done
    fi
}
