#!/bin/bash

alias x2goclient="x2goclient --home=\$HOME/.config"
alias mbsync="mbsync -c ~/.config/mbsync/mbsyncrc"
alias irssi="irssi --config ~/.config/irssi/config"
alias weechat="weechat --dir ~/.local/share/weechat"

