#!/bin/bash

dbus-daemon --syslog --session --address="unix:path=/run/user/1000/bus" &
#start-pulseaudio-x11
#exec /usr/libexec/geoclue-2.0/demos/agent & 
exec ~/bin/dwm/status_bar &
exec redshift &
exec compton --config ~/.config/compton/compton.conf &
exec feh --no-fehbg --bg-fill --randomize --recursive ~/pictures/wallpapers &
exec dwm

