#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

#menuentry "Gentoo Linux" {
	#set root=(hd0,gpt2)
	#linux /vmlinuz-4.14.83-gentoo root=UUID=d5c364f0-e76e-45f8-9836-39970e99d9e8
#	linux /vmlinuz-5.0.5-gentoo root=/dev/sda5 rw quiet
	#initrd /initramfs-genkernel-x86_64-4.14.83-gentoo
#}
if [ "${grub_platform}" == "efi" ]; then
	menuentry "Windows 10" --class=windows {
		insmod part_gpt
		insmod fat
		insmod chain
		search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275//disk@0,gpt2' --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2i A848-5CCC
		chainloader /EFI/Microsoft/Boot/bootmgfw.efi
	}
fi

menuentry "Shut Down" {
	echo "Shutting down..."
	halt
}

menuentry "Restart" {
	echo "Restarting..."
	reboot
}

menuentry "Firmware Setup" {
	fwsetup
}


