#!/bin/bash

#printf "%0.2f%%\n" $(xbacklight)
#printf "%0.2f%%\n" $(xbacklight)
current="$(cat /sys/class/backlight/intel_backlight/brightness)"
max="$(cat /sys/class/backlight/intel_backlight/max_brightness)"

printf "%.0f%%\n" $(echo "$current"/"$max"*100 | bc -l)
printf "%.0f%%\n" $(echo "$current"/"$max"*100 | bc -l)
